blank_issues_enabled: true

contact_links:
  - name: Get help in GitHub Discussions
    url: https://github.com/xjasonlyu/tun2socks/discussions
    about: Have a question? Not sure if your issue affects everyone reproducibly? The easiest way to get help is on GitHub Discussions!
