name: Feature Request
description: Suggest an idea for this project
title: "[Feature] "
body:
  - type: textarea
    attributes:
      label: Description
      description: A clear and concise description of what you want to happen.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Possible Solution
      description: (Optional) Any alternative solutions or features you've considered.
